/** Structured poster content — generated by AI */
export type PosterContent = {
  hook: string;
  summary: string;
  insights: string[];
  actions: string[];
  highlight: string;
};

/** Shared poster data structure — template-agnostic */
export type PosterData = {
  bookTitle: string;
  content: PosterContent;
};

/** Available poster template IDs */
export type PosterTemplate = "minimal-white" | "ai-code" | "cute" | "magazine";
